version: '3.7'
services:
  api:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '80:80'
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 80
  mongo:
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    image: mongo:4.2.0
